
services:

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fastapi_demo_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    environment:
      # - DEBUG=False
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/fastapi_demo_db
      - KEYCLOAK_URL=http://localhost:18080
      - KEYCLOAK_REALM=FastAPIDemo
      - KEYCLOAK_AUDIENCE=account
      - KEYCLOAK_CLIENT_ID=api-client
      - KEYCLOAK_CLIENT_SECRET=
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  postgres_data:
