
services:
  app:
    build: .
    container_name: fastapi_demo
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    # depends_on:
    #   - db

#   db:
#     image: postgres:15-alpine
#     container_name: postgres_db
#     environment:
#       POSTGRES_USER: user
#       POSTGRES_PASSWORD: password
#       POSTGRES_DB: meu_banco
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:
